-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Waktu pembuatan: 13 Okt 2025 pada 03.07
-- Versi server: 10.4.32-MariaDB
-- Versi PHP: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `db_budaya`
--

-- --------------------------------------------------------

--
-- Struktur dari tabel `data_budaya`
--

CREATE TABLE `data_budaya` (
  `id` int(11) NOT NULL,
  `nama` varchar(255) NOT NULL,
  `kategori` enum('Tari Klasik','Alat Musik','Lagu Klasik','Dongeng','Makanan Khas','Minuman Khas','Pakaian Adat','Rumah Adat','Destinasi') NOT NULL,
  `gambar` varchar(255) DEFAULT NULL,
  `video_url` varchar(500) DEFAULT NULL,
  `deskripsi` text DEFAULT NULL,
  `tanggal` date NOT NULL,
  `admin_id` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data untuk tabel `data_budaya`
--

INSERT INTO `data_budaya` (`id`, `nama`, `kategori`, `gambar`, `video_url`, `deskripsi`, `tanggal`, `admin_id`, `created_at`, `updated_at`) VALUES
(3, 'BONANG', 'Alat Musik', 'budaya_1759390867.jpg', 'https://youtu.be/Kzr0BzzIB3A?si=GYphEoRBH4BFkqYZ', 'Alat musik bonang adalah instrumen tradisional yang berasal dari Indonesia, khususnya Jawa dan Bali, yang merupakan bagian penting dari gamelan', '2025-10-02', 6, '2025-10-02 07:41:07', '2025-10-02 07:45:14'),
(4, 'GONG', 'Alat Musik', 'budaya_1759390936.jpg', 'https://youtube.com/shorts/XoWX3BLGhlY?si=eTPEJ99m81dbvIt3', 'Gong merupakan sebuah alat musik pukul yang terkenal di Asia Tenggara dan Asia Timur. Gong ini digunakan untuk alat musik tradisional. Saat ini tidak banyak lagi perajin gong seperti ini. Gong yang telah ditempa belum dapat ditentukan nadanya. Nada gong baru terbentuk setelah dibilas dan dibersihkan.', '2025-10-02', 6, '2025-10-02 07:42:16', '2025-10-02 07:42:16'),
(5, 'KENONG', 'Alat Musik', 'budaya_1759390992.jpg', 'https://youtube.com/shorts/bFwjoF6nMkE?si=s58mUbvRA1oqj3SP', 'Kenong adalah alat musik gamelan Jawa yang bernada tinggi dan nyaring dibuat dari perunggu, termasuk dalam keluarga gong. Kenong diletakkan pada posisi telungkup pada dua utas tali yang direntangkan bersilang pada sebuah landasan yang disebut rancakan.', '2025-10-02', 6, '2025-10-02 07:43:12', '2025-10-02 07:43:12'),
(6, 'KENDANG', 'Alat Musik', 'budaya_1759391071.jpg', 'https://youtu.be/VxEqrLyhkQ0?si=4pg9HE2N1XivtQ1U', 'Kendang atau Gendang adalah alat bunyi-bunyian berupa kayu bulat panjang, di dalamnya ada rongga dan salah satu lubangnya atau kedua-duanya diberi kulit yang berasal dari Jawa Alat musik ini termasuk salah satu bagian dalam gamelan dan karawitan Jawa.', '2025-10-02', 6, '2025-10-02 07:44:31', '2025-10-02 07:44:31'),
(7, 'SARON', 'Alat Musik', 'budaya_1759391175.jpg', 'https://youtu.be/pNTsBWwBdJk?si=N_RJi8z5oFZKZBre', 'Saron adalah alat musik perkusi tradisional Indonesia dari budaya Gamelan Jawa, terdiri dari bilah-bilah logam yang dipukul dengan palu kayu (gandhen). Alat ini menghasilkan suara nada tinggi dan termasuk dalam keluarga instrumen gamelan balungan.', '2025-10-02', 6, '2025-10-02 07:46:15', '2025-10-02 07:46:15'),
(8, 'SITER', 'Alat Musik', 'budaya_1759391212.jpeg', 'https://youtu.be/OlwMyu1l6DY?si=_k51liadysBS1CQ0', 'Siter adalah alat musik petik yang berdawai, bentuknya mirip kecapi Sunda. Siter juga bagian alat musik yang terdapat dalam gamelan Jawa. Umumnya, siter memiliki panjang 30 cm. Siter memiliki dua jenis senar, yaitu senar yang berjumlah 11 dan senar yang berjumlah 13.', '2025-10-02', 6, '2025-10-02 07:46:52', '2025-10-02 07:46:52'),
(9, 'Ande-Ande Lumut', 'Dongeng', 'budaya_1759391369.jpg', 'https://youtu.be/0xHskliONzw?si=vroAqNqwrF9SqaOX', 'Ande-Ande Lumut adalah dongeng asal Jawa Timur tentang pangeran yang mencari istri berhati baik. Kleting Kuning berhasil terpilih karena jujur dan rendah hati. Ceritanya mengajarkan nilai kejujuran dan kebaikan hati.', '2025-10-02', 6, '2025-10-02 07:49:29', '2025-10-06 01:11:41'),
(10, 'Jaka tarub dan 7 Bidadari', 'Dongeng', 'budaya_1759391412.png', 'https://youtu.be/7LMLLtJ8erc?si=1qbtDQ-YrkfmYNpZ', 'Jaka Tarub adalah dongeng asal Jawa Tengah tentang pemuda yang mencuri selendang bidadari Nawang Wulan. Saat rahasianya terbongkar, sang bidadari kembali ke kahyangan. Ceritanya mengajarkan kejujuran dan tanggung jawab.', '2025-10-02', 6, '2025-10-02 07:50:12', '2025-10-06 01:12:31'),
(11, 'Rawa Pening', 'Dongeng', 'budaya_1759391564.jpg', 'https://youtu.be/QuCYY5A8SNU?si=NcDPQdUW639PWHaO', 'Asal Usul Rawa Pening berasal dari Ambarawa, Jawa Tengah. Kisahnya tentang Baruklinting yang menenggelamkan desa sombong hingga terbentuklah Rawa Pening. Ceritanya mengajarkan pentingnya menghormati orang lain.', '2025-10-02', 6, '2025-10-02 07:52:44', '2025-10-06 01:12:54'),
(12, 'Roro Jonggrang', 'Dongeng', 'budaya_1759391600.jpg', 'https://youtu.be/p-fhWU6KIuU?si=Zr9zJ-OsYDoeCj1b', 'Roro Jonggrang adalah legenda dari Jawa Tengah tentang putri yang menipu Bandung Bondowoso saat membangun seribu candi. Akibatnya, ia dikutuk menjadi patung ke-1000. Ceritanya mengajarkan akibat dari kecurangan.', '2025-10-02', 6, '2025-10-02 07:53:20', '2025-10-06 01:13:21'),
(13, 'Timun Mas', 'Dongeng', 'budaya_1759391631.png', 'https://youtu.be/RVwJb91n1sY?si=eY2xQeClPG0WF5z3', 'Timun Mas adalah dongeng dari Jawa Tengah tentang gadis yang lahir dari timun emas dan dikejar raksasa. Dengan bantuan benda ajaib dari seorang pertapa, ia berhasil menyelamatkan diri. Ceritanya mengajarkan keberanian dan kecerdikan.', '2025-10-02', 6, '2025-10-02 07:53:51', '2025-10-06 01:13:51'),
(14, 'Cublak Cublak Suweng', 'Lagu Klasik', 'budaya_1759391740.jpg', 'https://youtu.be/BWeNBwo1ijY?si=B2QEiA41aV6Xf7TZ', 'Lagu Cublak-Cublak Suweng berasal dari Jawa Tengah dan termasuk dalam kategori lagu dolanan, yaitu lagu yang dinyanyikan sambil bermain. Permainan ini biasanya dimainkan oleh anak-anak dengan cara menebak benda kecil yang disembunyikan di tangan salah satu peserta. Walaupun terlihat sederhana, lagu ini memiliki makna yang mendalam. “Suweng” atau anting dijadikan simbol harta benda, dan melalui lagu ini masyarakat diajarkan bahwa harta bukanlah tujuan utama hidup. Yang lebih penting adalah budi pekerti, kejujuran, serta sikap saling bekerja sama. Lagu ini tidak hanya menghibur tetapi juga menjadi sarana pendidikan karakter bagi anak-anak sejak dini.', '2025-10-02', 6, '2025-10-02 07:55:40', '2025-10-02 11:00:14'),
(15, 'Gambang Suling', 'Lagu Klasik', 'budaya_1759391773.jpg', 'https://youtu.be/xdFMp0UnLWs?si=YJ0gHa1sx4TodylL', 'Lagu Gambang Suling adalah salah satu lagu daerah Jawa Tengah yang terkenal karena nuansa musiknya yang lembut dan menenangkan. Judul lagu ini diambil dari dua instrumen musik tradisional, yaitu “gambang” dan “suling”, yang sering dimainkan dalam pertunjukan gamelan Jawa. Lagu ini tidak hanya sekadar menggambarkan keindahan bunyi alat musik tradisional, tetapi juga mencerminkan kekayaan budaya Jawa yang penuh nilai seni. Melalui lantunan musiknya, “Gambang Suling” mampu menghadirkan suasana damai, syahdu, dan penuh ketenangan. Hingga kini, lagu ini sering ditampilkan dalam berbagai acara seni dan upacara adat Jawa sebagai bentuk pelestarian budaya', '2025-10-02', 6, '2025-10-02 07:56:13', '2025-10-02 11:00:37'),
(16, 'Gundul Gundul Pacul', 'Lagu Klasik', 'budaya_1759391810.jpg', 'https://youtu.be/JhH6SLBYqIE?si=CQIDoV5MgqvRVSqG', 'Lagu Gundul-Gundul Pacul adalah lagu dolanan Jawa Tengah yang sederhana tetapi sarat makna filosofi. Kata “gundul” berarti botak, sedangkan “pacul” adalah cangkul, alat yang digunakan untuk bertani. Lagu ini menjadi simbol tentang amanah dan tanggung jawab seorang pemimpin. Pemimpin diibaratkan membawa pacul untuk mengolah tanah demi kesejahteraan rakyat. Namun, jika pemimpin bersikap sombong, lalai, atau tidak jujur, maka amanah itu akan “jatuh” dan membahayakan masyarakat. Lagu ini mengandung pesan moral bahwa seorang pemimpin sejati harus rendah hati, mengutamakan kepentingan rakyat, dan menjauhkan diri dari keserakahan.', '2025-10-02', 6, '2025-10-02 07:56:50', '2025-10-02 11:01:04'),
(17, 'Lir Ilir', 'Lagu Klasik', 'budaya_1759391844.jpg', 'https://youtu.be/ZDGhJ4ToP2k?si=eKxSkLwlTLtpb6tT', 'Lagu Lir Ilir diciptakan oleh Sunan Kalijaga, salah satu anggota Wali Songo yang terkenal menggunakan seni dan budaya dalam menyebarkan agama Islam di Jawa. Lagu ini menggunakan lirik simbolis yang penuh makna. Kata “lir-ilir” berarti bangun atau sadar, sebagai ajakan agar manusia bangkit dari kelalaian hidup dan memperbarui iman. Bagian lirik yang menggambarkan tanaman hijau subur melambangkan kesempatan hidup yang penuh berkah, sedangkan ajakan untuk mengenakan pakaian hijau melambangkan kesucian iman. Lagu ini mengajarkan bahwa kehidupan di dunia adalah kesempatan untuk memperbanyak ibadah dan selalu mengingat Sang Pencipta', '2025-10-02', 6, '2025-10-02 07:57:24', '2025-10-02 11:01:23'),
(18, 'Suwe Ora Jamu', 'Lagu Klasik', 'budaya_1759391878.jpg', 'https://youtu.be/NLiGaO3o-to?si=M-BwjpTUSkJqc5N4', 'Lagu Suwe Ora Jamu adalah lagu rakyat Jawa yang sederhana tetapi penuh makna kehidupan. Dengan nada yang riang, lagu ini sering dinyanyikan dalam suasana santai maupun dalam kegiatan kebersamaan masyarakat. Lirik “suwe ora jamu” berarti sudah lama tidak minum jamu, namun memiliki makna kiasan “sudah lama tidak bertemu atau jarang bersilaturahmi.” Lagu ini menggambarkan kerinduan sekaligus pentingnya menjaga hubungan baik dengan sesama. Selain sebagai hiburan, lagu ini juga menjadi pengingat bahwa silaturahmi dan kebersamaan adalah nilai penting dalam kehidupan bermasyarakat.', '2025-10-02', 6, '2025-10-02 07:57:58', '2025-10-02 11:01:39'),
(19, 'Tari Kretek', 'Tari Klasik', 'budaya_1759403052.jpg', 'https://youtu.be/qBXa8mA7miI?si=mdBRQzxd9bjSSFqh', 'Tari Kretek adalah tarian khas Kudus, Jawa Tengah, yang menggambarkan proses pembuatan rokok kretek, mulai dari memetik tembakau hingga melintingnya. Gerakannya lincah dan energik, mencerminkan semangat kerja keras masyarakat Kudus. Tarian ini biasanya ditampilkan dalam festival budaya dan penyambutan tamu.', '2025-10-02', 6, '2025-10-02 11:04:12', '2025-10-02 11:04:12'),
(20, 'Tari Prawiroguno', 'Tari Klasik', 'budaya_1759403100.jpg', 'https://youtu.be/f-m6WwJW5ug?si=ovTs_TO9uNNCe0v6', 'Tari Prawiroguno adalah tarian khas Kebumen, Jawa Tengah, yang menggambarkan keberanian prajurit dengan gerakan tegas dan dinamis. Penari memakai kostum prajurit lengkap dengan senjata, melambangkan semangat perjuangan dan kepahlawanan.', '2025-10-02', 6, '2025-10-02 11:05:00', '2025-10-02 11:05:00'),
(21, 'Tari Kukilo', 'Tari Klasik', 'budaya_1759403160.jpg', 'https://youtu.be/wzInjK4XsQg?si=aYitR8USBLf2r6Sy', 'Tari Kukilo adalah tarian tradisional dari Jawa Tengah yang menggambarkan tingkah laku burung perkutut (kukilo) yang lincah dan indah. Gerakannya lembut, gemulai, namun tetap dinamis, melambangkan keanggunan serta keceriaan. Tari ini biasanya dibawakan dalam acara budaya atau penyambutan tamu sebagai hiburan dan simbol keindahan alam.', '2025-10-02', 6, '2025-10-02 11:06:00', '2025-10-02 11:06:00'),
(22, 'Tari Jlantur', 'Tari Klasik', 'budaya_1759403223.jpg', 'https://youtu.be/6fHWrepmVg8?si=ZxUtLHVftJVSMNOU', 'Tari Jlantur berasal dari Boyolali, Jawa Tengah, yang menggambarkan semangat prajurit berkuda. Penari biasanya berjumlah banyak dengan kostum prajurit dan properti kuda tiruan. Gerakannya gagah, kompak, dan dinamis, melambangkan keberanian serta kebersamaan dalam perjuangan.', '2025-10-02', 6, '2025-10-02 11:07:03', '2025-10-02 11:07:03'),
(23, 'Tari Gambyong', 'Tari Klasik', 'budaya_1759403289.jpg', 'https://youtu.be/GlRBdMmzgPY?si=8qFXAcG1H1l3QzlP', 'Tari Gambyong adalah tarian tradisional dari Surakarta, Jawa Tengah, yang awalnya digunakan untuk upacara kesuburan. Gerakannya lemah gemulai, anggun, dan selaras dengan irama gamelan. Penari biasanya memakai kebaya dengan selendang, melambangkan keindahan, kelembutan, dan keanggunan wanita Jawa.', '2025-10-02', 6, '2025-10-02 11:08:09', '2025-10-02 11:08:09'),
(24, 'Tari Beksan Wireng', 'Tari Klasik', 'budaya_1759403343.jpg', 'https://youtu.be/Sk3jcscEXac?si=hrmyWyRWFNGpAQ92', 'Tari Beksan Wireng adalah tarian tradisional Jawa yang menggambarkan latihan keprajuritan para prajurit. Gerakannya tegas, gagah, dan berpasangan, sering menggunakan senjata seperti pedang atau tombak. Tarian ini melambangkan keberanian, kedisiplinan, serta semangat kepahlawanan.', '2025-10-02', 6, '2025-10-02 11:09:03', '2025-10-02 11:09:03'),
(25, 'Pakaian Adat Surjan', 'Pakaian Adat', 'budaya_1759403570.jpg', 'https://youtube.com/shorts/9d5zdTdpSyI?si=55YGI7T9aFbycqly', 'Surjan adalah pakaian tradisional Jawa yang biasanya dikenakan oleh pria. Bentuknya seperti kemeja dengan lengan panjang dan motif lurik (garis-garis). Surjan sering dipadukan dengan kain jarik batik sebagai bawahan dan blangkon sebagai penutup kepala. Dahulu, surjan tidak hanya digunakan oleh kalangan bangsawan, tetapi juga oleh masyarakat biasa, terutama saat menghadiri upacara adat dan kegiatan resmi. Surjan melambangkan kesederhanaan, kesopanan, sekaligus kewibawaan pria Jawa.', '2025-10-02', 6, '2025-10-02 11:12:50', '2025-10-02 11:12:50'),
(26, 'Pakaian Adat Kebaya', 'Pakaian Adat', 'budaya_1759403638.jpeg', 'https://youtube.com/shorts/HUv5yhUKIWg?si=OR_sAn8iAse6Yo6l', 'Kebaya adalah busana tradisional Jawa yang identik dengan perempuan. Bentuknya berupa atasan berbahan tipis, seperti brokat atau katun, dengan potongan anggun yang dipadukan dengan bawahan berupa kain batik. Kebaya melambangkan kelembutan, keanggunan, dan kesopanan wanita Jawa. Kebaya biasanya digunakan pada acara-acara penting seperti pernikahan, upacara adat, maupun acara resmi. Sampai sekarang, kebaya masih dilestarikan dan dipakai pada peringatan Hari Kartini maupun acara nasional lainnya.', '2025-10-02', 6, '2025-10-02 11:13:58', '2025-10-02 11:13:58'),
(27, 'Pakaian Adat Kanigaran', 'Pakaian Adat', 'budaya_1759403719.jpg', 'https://youtube.com/shorts/D6CFSbnwzkI?si=rngWjCrezHHhej5L', 'Kanigaran adalah pakaian adat Jawa yang sangat mewah dan penuh simbol kebesaran. Pakaian ini biasanya dipakai oleh kaum bangsawan atau keluarga keraton dalam acara yang bersifat sakral, seperti pernikahan adat Jawa yang memiliki aturan khusus. Busana kanigaran menonjolkan kemegahan dengan hiasan dan aksesoris yang melambangkan kewibawaan serta status sosial tinggi. Karena kesakralannya, pakaian ini tidak bisa dipakai sembarangan dan biasanya digunakan hanya dalam upacara adat tertentu.', '2025-10-02', 6, '2025-10-02 11:15:19', '2025-10-02 11:15:19'),
(28, 'Pakaian Adat Dodot Basahan', 'Pakaian Adat', 'budaya_1759403776.jpg', 'https://youtube.com/shorts/XkWAhcxysEQ?si=AQ_ja9hxaxHzAppV', 'Dodot Basahan adalah pakaian adat Jawa yang sangat khas dan biasa digunakan dalam pernikahan adat, khususnya pada prosesi panggih atau temu manten. Bentuknya berupa kain panjang (dodot) berukuran besar yang dililitkan menutupi tubuh. Dodot basahan dikenakan baik oleh mempelai pria maupun wanita. Penggunaan dodot melambangkan kesakralan, keagungan, serta penghormatan terhadap adat Jawa. Karena bentuknya yang mewah, dodot basahan sering dianggap sebagai salah satu busana adat tertinggi dalam budaya Jawa', '2025-10-02', 6, '2025-10-02 11:16:16', '2025-10-02 11:16:16'),
(29, 'Pakaian Adat Beskap', 'Pakaian Adat', 'budaya_1759403917.jpg', 'https://youtube.com/shorts/0o0BZ42QqPw?si=Kt5Us5Whj_UmSBWh¬¬', 'Beskap adalah pakaian adat Jawa untuk pria yang berbentuk seperti jas tradisional dengan kancing yang tidak lurus di tengah, melainkan agak miring ke samping. Beskap biasanya dipadukan dengan jarik batik sebagai bawahan, serta blangkon atau kuluk sebagai penutup kepala. Pakaian ini sering digunakan dalam acara resmi, seperti pernikahan, upacara adat, atau penyambutan tamu kehormatan. Beskap melambangkan kerapian, wibawa, dan kesopanan seorang pria Jawa. Hingga kini, beskap masih sering digunakan oleh pengantin pria dalam pernikahan adat Jawa.', '2025-10-02', 6, '2025-10-02 11:17:10', '2025-10-02 11:18:37'),
(30, 'Pakaian Adat Basahan Perempuan', 'Pakaian Adat', 'budaya_1759403893.jpg', 'https://youtube.com/shorts/jMyca05T-fk?si=_kXtK_XHIbjH7r9R', 'Basahan perempuan adalah busana adat yang dikenakan oleh mempelai wanita dalam upacara pernikahan adat Jawa. Bentuknya dipadukan dengan dodot (kain panjang) yang dililitkan serta tata rias khas Jawa yang lengkap, seperti paes pada dahi, sanggul besar, dan perhiasan emas. Pakaian ini melambangkan kesucian, keanggunan, sekaligus status sakral seorang perempuan yang memasuki jenjang pernikahan. Busana basahan perempuan hanya digunakan pada upacara tertentu karena memiliki makna mendalam tentang kehidupan rumah tangga menurut adat Jawa.', '2025-10-02', 6, '2025-10-02 11:18:13', '2025-10-02 11:18:13'),
(31, 'Air Terjun Sri Gethuk', 'Destinasi', 'budaya_1759407703.jpg', 'https://youtube.com/shorts/QSEi2AFdq5M?si=oLPsALxsXB8Z9GzP', 'Air Terjun Sri Gethuk adalah wisata alam di Gunungkidul yang terkenal dengan aliran airnya yang jernih di antara tebing-tebing karst. Letaknya di tepi Sungai Oyo membuat suasananya semakin eksotis, dan pengunjung bisa menikmati keindahannya sambil naik perahu atau bermain air di bawah terjunannya.', '2025-10-02', 6, '2025-10-02 12:21:43', '2025-10-02 12:21:43'),
(32, 'Candi Borobudur', 'Destinasi', 'budaya_1759407754.jpg', 'https://youtube.com/shorts/BbPF0k8fXVk?si=b_0f1YwuuZwz6lda', 'Candi Borobudur adalah candi Buddha terbesar di dunia yang terletak di Magelang, Jawa Tengah. Dibangun pada abad ke-8 oleh Dinasti Syailendra, candi ini berbentuk stupa raksasa dengan relief indah yang menceritakan ajaran Buddha. Borobudur juga menjadi warisan budaya dunia UNESCO dan salah satu destinasi wisata paling terkenal di Indonesia.', '2025-10-02', 6, '2025-10-02 12:22:34', '2025-10-02 12:22:34'),
(33, 'Candi Prambanan', 'Destinasi', 'budaya_1759407800.jpg', 'https://youtube.com/shorts/VdBpwR6v030?si=OrWARjEGGfUmipy0', 'Candi Prambanan adalah candi Hindu terbesar di Indonesia yang terletak di perbatasan Yogyakarta dan Jawa Tengah. Candi ini dibangun pada abad ke-9 oleh Rakai Pikatan dan dipersembahkan untuk Trimurti: Siwa, Wisnu, dan Brahma. Arsitektur candi utama setinggi 47 meter dengan relief kisah Ramayana membuatnya sangat megah. Kini, Prambanan menjadi warisan dunia UNESCO sekaligus destinasi wisata sejarah terkenal.', '2025-10-02', 6, '2025-10-02 12:23:20', '2025-10-02 12:23:20'),
(34, 'Dieng Plateau', 'Destinasi', 'budaya_1759407843.jpg', 'https://youtube.com/shorts/ezE3VUqxvlE?si=cV2An1t_IqhctHNC', 'Dieng Plateau adalah kawasan pegunungan di Jawa Tengah yang terkenal dengan panorama alam menawan, telaga warna-warni, serta peninggalan candi Hindu kuno. Suasana sejuk dan keunikan budayanya membuat Dieng dijuluki “Negeri di Atas Awan.”', '2025-10-02', 6, '2025-10-02 12:24:03', '2025-10-02 12:24:03'),
(35, 'Lawang Sewu', 'Destinasi', 'budaya_1759407882.jpg', 'https://youtu.be/BxL6fvWlXoU?si=H1BVM_XkYsE8_fER', 'Lawang Sewu adalah gedung bersejarah di Semarang, Jawa Tengah, yang dibangun pada awal abad ke-20 sebagai kantor perusahaan kereta api Belanda. Nama \"Lawang Sewu\" berarti \"seribu pintu\" karena memiliki banyak pintu dan jendela besar. Bangunan bergaya arsitektur kolonial ini kini menjadi destinasi wisata populer, sekaligus ikon kota Semarang yang sarat nilai sejarah.', '2025-10-02', 6, '2025-10-02 12:24:42', '2025-10-02 12:24:42'),
(36, 'Pantai Kartini', 'Destinasi', 'budaya_1759407920.jpg', 'https://youtube.com/shorts/ZFVs4V9Nu_M?si=AVT1BY2lt1Y0aiTL', 'Pantai Kartini terletak di Jepara, Jawa Tengah. Pantai ini terkenal sebagai objek wisata keluarga dengan pemandangan laut yang indah, ombak tenang, dan fasilitas rekreasi. Selain menikmati panorama pantai, pengunjung bisa menjelajahi wahana seperti Kura-kura Ocean Park dan dermaga yang menjadi ikon Pantai Kartini. Tempat ini juga kerap digunakan untuk acara budaya dan menjadi jalur menuju Karimunjawa.', '2025-10-02', 6, '2025-10-02 12:25:20', '2025-10-02 12:25:20'),
(37, 'Pulau Panjang', 'Destinasi', 'budaya_1759407960.jpg', 'https://youtube.com/shorts/6O7pRrFvCpM?si=SUso3W8Vqj-iMLYF', 'Pulau Panjang di Jepara adalah pulau kecil nan eksotis dengan pasir putih halus, laut jernih bergradasi biru, dan hutan mangrove yang masih asri. Pulau ini cocok untuk snorkeling, berkemah, atau sekadar berjalan santai mengelilinginya karena ukurannya yang tidak terlalu luas. Suasananya tenang dan alami, menjadikannya tempat ideal untuk melepas penat sekaligus menikmati pesona tropis ala pulau pribadi.', '2025-10-02', 6, '2025-10-02 12:26:00', '2025-10-02 12:26:00'),
(38, 'Taman Bunga Celosia', 'Destinasi', 'budaya_1759407997.jpg', 'https://youtube.com/shorts/RDewy_CJ9fg?si=ajYS9zabpLAMR7V5', 'Taman Bunga Celosia di Bandungan, Semarang, adalah destinasi wisata penuh warna dengan hamparan bunga celosia, lavender, hingga berbagai bunga hias lainnya yang tersusun rapi dan indah. Selain spot foto instagramable berlatar Gunung Ungaran, taman ini juga dilengkapi wahana unik seperti rumah kaca Belanda, miniatur landmark dunia, dan area bermain. Suasananya sejuk dan ceria, membuat pengunjung betah berlama-lama menikmati keindahan alam sekaligus berfoto di setiap sudutnya.', '2025-10-02', 6, '2025-10-02 12:26:37', '2025-10-02 12:26:37'),
(39, 'Rumah Adat Joglo', 'Rumah Adat', 'budaya_1759408103.jpg', 'https://youtube.com/shorts/K3PrZAdudPE?si=9pn7GzEVRjVlhYNy', 'Rumah adat Joglo adalah rumah tradisional khas Jawa Tengah yang memiliki bentuk atap unik menyerupai trapesium bertingkat dengan bagian tengah lebih tinggi. Joglo biasanya digunakan oleh kalangan bangsawan atau orang terpandang pada masa lalu. Ciri khasnya terletak pada soko guru (empat tiang utama penyangga) di tengah rumah, ruang luas tanpa sekat, serta ukiran kayu bernuansa Jawa', '2025-10-02', 6, '2025-10-02 12:28:23', '2025-10-02 12:28:23'),
(40, 'Rumah Adat Limasan', 'Rumah Adat', 'budaya_1759408150.jpg', 'https://youtube.com/shorts/5nOm1g63oas?si=AHn_y-1NDvefznE2', 'Rumah adat Limasan adalah salah satu rumah tradisional khas Jawa Tengah yang memiliki atap berbentuk limas dengan empat sisi miring. Bentuk atapnya sederhana namun kokoh, biasanya dibuat dari kayu jati dengan penutup genteng tanah liat. Rumah Limasan sering dipakai oleh masyarakat Jawa sebagai rumah tinggal karena strukturnya mampu menahan panas dan hujan dengan baik. Selain itu, rumah ini mencerminkan kesederhanaan, keteraturan, dan kearifan lokal masyarakat Jawa.', '2025-10-02', 6, '2025-10-02 12:29:10', '2025-10-02 12:29:10'),
(41, 'Adon Adon Coro', 'Minuman Khas', 'budaya_1759573008.jpg', 'https://youtu.be/PbDFzvwi9tw?si=NwtwLbkU8Zlge-oL', 'Adon-adon Coro adalah minuman tradisional khas Kudus, Jawa Tengah. Minuman ini terbuat dari campuran santan, jahe, merica, serai, kayu manis, dan rempah-rempah lainnya yang disajikan hangat. Rasanya gurih, pedas hangat, dan manis, sehingga dipercaya bermanfaat untuk menghangatkan tubuh serta menjaga stamina.', '2025-10-04', 6, '2025-10-04 10:16:48', '2025-10-04 10:16:48'),
(42, 'Dawet Ireng', 'Minuman Khas', 'budaya_1759573063.jpg', 'https://youtu.be/C9w6AttPWok?si=ENY7W5s_oFo2idHp', 'Dawet Ireng adalah minuman tradisional khas Purworejo, Jawa Tengah, yang terbuat dari cendol berwarna hitam (ireng) hasil olahan tepung beras dengan abu merang. Minuman ini disajikan dengan santan, gula jawa cair, dan es, menghasilkan rasa manis, gurih, dan segar.', '2025-10-04', 6, '2025-10-04 10:17:43', '2025-10-04 10:17:43'),
(43, 'Dawet Ayu', 'Minuman Khas', 'budaya_1759573122.png', 'https://youtu.be/k4VzfeRUBvI?si=CR9bantVY0Y-qCpz', 'Dawet Ayu adalah minuman tradisional khas Banjarnegara, Jawa Tengah. Minuman ini berisi cendol hijau dari tepung beras, disajikan dengan santan, gula merah cair, dan es, sehingga rasanya manis, gurih, dan menyegarkan.', '2025-10-04', 6, '2025-10-04 10:18:42', '2025-10-04 10:18:42'),
(44, 'Kopi Joss', 'Minuman Khas', 'budaya_1759573170.jpg', 'https://youtu.be/VNiiMaiux-0?si=E_t55opOl6ao3DX0', 'Kopi Joss adalah minuman khas Yogyakarta berupa kopi hitam panas yang disajikan dengan arang membara langsung dicelupkan ke dalamnya. Proses ini memberi aroma khas, rasa unik, serta dipercaya dapat mengurangi kadar asam pada kopi.', '2025-10-04', 6, '2025-10-04 10:19:30', '2025-10-04 10:19:30'),
(45, 'Sekoteng', 'Minuman Khas', 'budaya_1759573242.jpg', 'https://youtube.com/shorts/ETEA9Mz2oxw?si=7aQQd64iprGTSazr', 'Sekoteng adalah minuman tradisional khas Jawa Tengah yang disajikan hangat dengan kuah jahe manis. Isinya biasanya kacang hijau, kacang tanah, potongan roti, pacar cina, dan kolang-kaling, sehingga rasanya hangat, manis, dan mengenyangkan.', '2025-10-04', 6, '2025-10-04 10:20:42', '2025-10-04 10:20:42'),
(46, 'Wedang Uwuh', 'Minuman Khas', 'budaya_1759573312.jpg', 'https://youtube.com/shorts/qSifISO5w8U?si=JfkgS0Z4jRQYqHB7', 'Wedang Uwuh adalah minuman tradisional khas Yogyakarta dan Jawa Tengah yang terbuat dari berbagai rempah seperti jahe, kayu manis, cengkeh, pala, daun secang, dan gula merah. Minuman ini disajikan hangat, berwarna merah kecokelatan, dan memiliki rasa manis, hangat, serta aromanya harum, sehingga dipercaya menyehatkan tubuh dan menghangatkan badan.', '2025-10-04', 6, '2025-10-04 10:21:52', '2025-10-04 10:21:52'),
(47, 'Getuk', 'Makanan Khas', 'budaya_1759672587.jpg', 'https://youtube.com/shorts/7oD9KcKycb8?si=sW-w9g8E0EzqMiZJ', 'Getuk adalah makanan ringan dari singkong yang direbus, kemudian dicampur gula pasir atau gula merah serta kelapa lalu ditumbuk sekaligus. Getuk adalah penganan tradisional khas masyarakat Jawa yang populer di wilayah Daerah Istimewa Yogyakarta, Jawa Tengah.', '2025-10-05', 6, '2025-10-05 13:56:27', '2025-10-05 13:56:27'),
(48, 'Lumpia Semarang', 'Makanan Khas', 'budaya_1759672682.jpg', 'https://youtube.com/shorts/Av5pzhJl3_U?si=zABtjVIvLBCKxEZn', 'Lumpia semarang adalah makanan semacam rollade yang berisi rebung, telur, dan daging ayam atau udang. Cita rasa lumpia semarang adalah perpaduan rasa antara Tionghoa dan Indonesia karena pertama kali dibuat oleh seorang keturunan Tionghoa yang menikah dengan orang Indonesia dan menetap di Semarang, Jawa Tengah.', '2025-10-05', 6, '2025-10-05 13:58:02', '2025-10-05 13:58:02'),
(49, 'Soto Kudus', 'Makanan Khas', 'budaya_1759672721.jpg', 'https://youtu.be/xzHhgrKcdPc?si=i3IGFHU_RJVpnW7B', 'Soto Kudus adalah soto yang berasal dari Kudus, Jawa Tengah. Soto kudus, hampir mirip dengan soto Lamongan, soto kudus berisi suwiran ayam dan taoge. Terkadang soto kudus juga menggunakan daging kerbau. Kuahnya lebih bening.', '2025-10-05', 6, '2025-10-05 13:58:41', '2025-10-05 13:58:41'),
(50, 'Tongseng', 'Makanan Khas', 'budaya_1759672759.jpg', 'https://youtube.com/shorts/-z5DsATG6u0?si=IiF_xYarIIMMrTW8', 'Tongseng adalah sejenis hidangan gulai daging berkuah dengan bumbu yang lebih kuat. Tongseng pada umumnya menggunakan daging kambing, meskipun ada pula tongseng daging sapi, daging domba, atau daging kerbau.', '2025-10-05', 6, '2025-10-05 13:59:19', '2025-10-05 13:59:19'),
(51, 'Wajik', 'Makanan Khas', 'budaya_1759672790.jpg', 'https://youtube.com/shorts/7ZdarkCT62E?si=DPcue8j6jtaCrjFQ', 'Wajik adalah hidangan tradisional khas pernikahan adat Jawa yang terbuat dari bahan dasar beras ketan, santan kelapa, dan gula merah. Kudapan yang sudah ada sejak jaman Majapahit ini, masuk dalam jajanan klasik khas Jawa Tengah.', '2025-10-05', 6, '2025-10-05 13:59:50', '2025-10-05 13:59:50'),
(52, 'Rebab', 'Alat Musik', 'budaya_1759757955.jpg', 'https://youtu.be/bE1p5KImWpk?si=k3irryF2lV04Rwum', 'Rebab adalah alat musik tradisional Jawa yang dimainkan dengan cara digesek dan menjadi salah satu instrumen penting dalam ansambel gamelan. Bentuknya khas, dengan tubuh kecil menyerupai mangkuk yang biasanya terbuat dari kayu atau tempurung kelapa. Bagian depan tubuh rebab ditutup dengan kulit tipis, yang berfungsi sebagai resonator untuk memperkuat getaran suara dari dawainya. Rebab umumnya memiliki dua atau tiga dawai logam yang digesek menggunakan busur khusus yang terbuat dari batang kayu lentur dengan rambut kuda sebagai senarnya. Bunyi yang dihasilkan rebab lembut, melengking, dan bergetar panjang, memberikan kesan emosional dan mendalam pada alunan musik gamelan. Dalam pertunjukan gamelan Jawa, rebab berfungsi sebagai pembawa melodi utama yang mengarahkan jalannya lagu, sementara alat musik lainnya mengikuti arahan nadanya. Rebab sering digunakan untuk mengiringi berbagai jenis kesenian tradisional seperti wayang kulit, tari klasik Jawa, dan tembang Jawa. Selain fungsi musikalnya, rebab juga memiliki nilai simbolis sebagai lambang kelembutan, keharmonisan, dan kehalusan rasa dalam budaya Jawa. Suaranya yang merdu dan penuh perasaan menjadikan rebab sebagai salah satu alat musik yang mencerminkan keindahan dan kedalaman jiwa masyarakat Jawa.', '2025-10-06', 6, '2025-10-06 13:39:15', '2025-10-06 13:39:15'),
(53, 'Gambang', 'Alat Musik', 'budaya_1759758117.jpg', 'https://youtu.be/R_Zxugz1a6I?si=yIwjJiKof-HEyzEc', 'Gambang adalah alat musik tradisional Jawa yang termasuk dalam perangkat gamelan dan dimainkan dengan cara dipukul. Alat musik ini terdiri dari bilah-bilah kayu berjumlah antara 18 hingga 21 buah, yang disusun berurutan di atas kotak kayu berfungsi sebagai resonator suara. Bilah-bilah tersebut terbuat dari kayu keras seperti kayu nangka, kayu sono, atau kayu jati, karena jenis kayu ini dapat menghasilkan bunyi yang nyaring dan merdu. Pemain gambang menggunakan sepasang pemukul kecil yang terbuat dari tanduk atau kayu ringan dengan ujung dilapisi kain agar bunyi yang dihasilkan lembut dan jelas. Dalam ansambel gamelan Jawa, gambang memiliki peran penting sebagai pengisi melodi dan penambah variasi nada di antara alat musik logam seperti saron atau bonang. Suaranya yang lembut, hangat, dan bergetar memberikan warna tersendiri dalam harmoni gamelan. Selain dalam gamelan, gambang juga digunakan dalam kesenian tradisional lain, seperti Gambang Kromong di Betawi, yang mendapat pengaruh dari alat musik gambang Jawa. Keindahan suara gambang mencerminkan kelembutan dan ketenangan, sehingga alat musik ini tidak hanya berfungsi sebagai pengiring, tetapi juga pembawa suasana dalam setiap pertunjukan tradisional.', '2025-10-06', 6, '2025-10-06 13:41:57', '2025-10-06 13:41:57'),
(54, 'Terompet Reog', 'Alat Musik', 'budaya_1759758301.jpg', 'https://youtu.be/OwnPvA9lQ30?si=EQps3-76RTIsanLy', 'Terompet Reog adalah alat musik tradisional yang digunakan dalam pertunjukan Reog Ponorogo, kesenian yang berasal dari daerah perbatasan Jawa Tengah dan Jawa Timur. Alat musik ini memiliki bentuk unik dengan corong besar di ujungnya dan bagian peniup yang panjang seperti seruling. Terompet Reog biasanya terbuat dari bambu, kayu, dan logam, dengan bagian corong sering dihias agar tampak menarik. Cara memainkannya adalah dengan ditiup kuat, menghasilkan suara yang keras, melengking, dan bergema menjadi ciri khas utama dalam pertunjukan Reog. Fungsi terompet Reog bukan hanya sebagai pengiring musik, tetapi juga sebagai pembangun suasana dramatis dan semangat dalam pertunjukan. Suaranya yang nyaring digunakan untuk memberi tanda perubahan adegan, mengiringi gerakan para penari, serta menambah kesan gagah dan berwibawa pada tokoh utama seperti Singo Barong. Dalam budaya Jawa, bunyi terompet Reog melambangkan kekuatan, keberanian, dan semangat juang, sehingga alat musik ini memiliki nilai simbolis yang tinggi. Perpaduan antara suara terompet, kendang, gong, dan alat musik lain menjadikan pertunjukan Reog Ponorogo terdengar megah, energik, dan memukau.', '2025-10-06', 6, '2025-10-06 13:45:01', '2025-10-06 13:45:01'),
(55, 'Seruling', 'Alat Musik', 'budaya_1759758393.jpg', 'https://youtu.be/8bXkufMNioI?si=HEyCLG0U91S51NQd', 'Seruling adalah alat musik tradisional yang dimainkan dengan cara ditiup, dan banyak ditemukan di berbagai daerah di Indonesia, termasuk di Jawa Tengah. Alat musik ini biasanya terbuat dari bambu tipis yang ringan namun kuat, dengan beberapa lubang nada di bagian depannya untuk menghasilkan berbagai tinggi nada. Panjang dan jumlah lubang seruling dapat bervariasi, tergantung pada jenis dan daerah asalnya.\r\nSeruling menghasilkan bunyi yang lembut, merdu, dan menenangkan, sehingga sering digunakan untuk mengiringi lagu-lagu tradisional, tembang Jawa, maupun pertunjukan gamelan. Pemain seruling meniup udara melalui lubang tiup sambil menutup dan membuka lubang nada untuk menghasilkan melodi. Dalam kebudayaan Jawa, seruling sering dianggap sebagai simbol ketenangan, kedamaian, dan kehalusan perasaan, karena suaranya yang lembut mampu menggambarkan suasana hati yang penuh kedamaian. Selain sebagai alat musik pengiring, seruling juga sering dimainkan secara solo untuk mengekspresikan keindahan dan keheningan alam pedesaan Jawa.', '2025-10-06', 6, '2025-10-06 13:46:33', '2025-10-06 13:46:33'),
(56, 'Dondong Opo Salak', 'Lagu Klasik', 'budaya_1759758658.jpg', 'https://youtu.be/JzlxDCemojM?si=fOl_RaNgDsqJklIB', 'Lagu Dondong Opo Salak adalah lagu dolanan Jawa Tengah yang memiliki lirik ringan namun penuh makna simbolis. Kata “dondong” dan “salak” adalah nama buah, namun digunakan sebagai kiasan dalam percakapan antara dua orang. Lagu ini biasanya digunakan untuk bermain tebak-tebakan sambil menumbuhkan interaksi sosial di antara anak-anak.\r\nMakna dari lagu ini ialah tentang pilihan dalam hidup dan pentingnya kesetiaan. Liriknya menyiratkan pesan bahwa dalam memilih teman, pasangan, atau jalan hidup, manusia harus berhati-hati agar tidak tertipu oleh penampilan luar.\r\nSelain mengandung nilai moral, lagu Dondong Opo Salak juga memperlihatkan kekayaan bahasa kiasan dalam budaya Jawa, di mana nasihat dan ajaran disampaikan melalui permainan kata yang ringan dan menghibur.', '2025-10-06', 6, '2025-10-06 13:50:58', '2025-10-06 13:50:58'),
(57, 'Sluku-Sluku Bathok', 'Lagu Klasik', 'budaya_1759758841.jpg', 'https://youtu.be/eVCbAIHEDy0?si=KCKHN10tmy9NUuZK', 'Lagu Sluku-Sluku Bathok juga berasal dari Jawa Tengah dan termasuk jenis lagu dolanan anak. Liriknya mengandung simbol dan filosofi Jawa yang mendalam. Kata “bathok” berarti tempurung kelapa, sementara “sluku-sluku” menggambarkan kegiatan menggoyang atau mengusap-usap.\r\nMakna lagu ini tidak hanya sebagai pengantar tidur anak, tetapi juga sebagai pengingat tentang kehidupan dan kematian. Baris “Sir-sir pong dele kopong” menggambarkan manusia yang hampa bila jauh dari Tuhan. “Bathoke ela-ela” melambangkan kepala atau akal pikiran, yang harus selalu digunakan dengan bijak.\r\nLagu ini mengajarkan agar manusia hidup sederhana, rendah hati, dan selalu ingat kepada Sang Pencipta. Meskipun berirama lembut dan menenangkan, Sluku-Sluku Bathok menyimpan pesan spiritual yang dalam dan mencerminkan kebijaksanaan lokal masyarakat Jawa.', '2025-10-06', 6, '2025-10-06 13:54:01', '2025-10-06 13:54:01'),
(58, 'Padang Bulan', 'Lagu Klasik', 'budaya_1759758950.jpg', 'https://youtu.be/H6jM9sf8_1E?si=U9ABfKRna0CwohSP', 'Lagu Padang Bulan adalah lagu rakyat yang sangat populer di berbagai daerah di Jawa, terutama di Jawa Tengah. Lagu ini memiliki melodi yang lembut dan sering dinyanyikan pada malam hari di acara-acara santai. Liriknya menggambarkan suasana indah ketika bulan bersinar terang di langit malam, simbol dari kebahagiaan, kehangatan, dan rasa syukur.\r\nDalam budaya Jawa, bulan purnama sering dikaitkan dengan keberkahan dan ketenangan hati. Lagu ini juga menjadi simbol kerukunan dan kebersamaan, karena biasanya dinyanyikan secara bersama-sama sambil berkumpul di bawah sinar bulan.\r\nSelain sebagai hiburan, lagu Padang Bulan juga mengandung pesan agar manusia selalu bersyukur atas keindahan alam ciptaan Tuhan dan menjadikan waktu malam sebagai saat untuk beristirahat dan merenung.', '2025-10-06', 6, '2025-10-06 13:55:50', '2025-10-06 13:55:50'),
(59, 'Pitik Tukung', 'Lagu Klasik', 'budaya_1759759050.jpg', 'https://youtu.be/KwNFFhMcBEk?si=sFrIWiX9cS6ig4g-', 'Lagu Pitik Tukung berarti “anak ayam yang pincang”. Lagu ini sering dinyanyikan oleh anak-anak di Jawa Tengah sebagai lagu dolanan dengan irama ceria. Namun di balik kesederhanaannya, terdapat nilai moral yang kuat.\r\nLiriknya menggambarkan seekor anak ayam yang pincang namun tetap berusaha berjalan. Hal ini mengajarkan tentang ketekunan, semangat hidup, dan rasa empati terhadap sesama. Masyarakat Jawa percaya bahwa kekurangan bukanlah alasan untuk menyerah, tetapi justru menjadi dorongan untuk terus berusaha.\r\nLagu ini juga mengandung pesan agar anak-anak belajar menghargai perbedaan dan membantu teman yang memiliki keterbatasan. Dengan demikian, Pitik Tukung berfungsi sebagai sarana pendidikan moral dan sosial bagi anak-anak sejak dini.', '2025-10-06', 6, '2025-10-06 13:57:30', '2025-10-06 13:57:30'),
(60, 'Ande-Ande Lumut', 'Lagu Klasik', 'budaya_1759759244.jpg', 'https://youtu.be/oDS0_QRUMbQ?si=WU6jWhxsgo4r8qGe', 'Berbeda dari lagu dolanan biasa, Ande-Ande Lumut adalah lagu yang diadaptasi dari kisah rakyat Jawa Tengah yang terkenal. Cerita ini berkisah tentang Ande-Ande Lumut, seorang pemuda tampan dan bijaksana yang mencari calon istri sejati. Dalam perjalanan cerita, banyak gadis cantik datang mencoba memikatnya, tetapi hanya Kleting Kuning, gadis sederhana dan berhati mulia, yang berhasil memenangkan hatinya.\r\nMakna lagu Ande-Ande Lumut sangat dalam, yaitu tentang kesetiaan, kejujuran, dan kemurnian hati. Lagu ini menegaskan bahwa kecantikan sejati bukan berasal dari penampilan luar, melainkan dari kebaikan dan keikhlasan hati.\r\nSelain menjadi hiburan rakyat, lagu ini juga merupakan bentuk pelestarian cerita rakyat Jawa yang sarat nilai moral dan etika sosial. Biasanya lagu ini dinyanyikan dalam pertunjukan drama tradisional, tari, atau sendratari yang mengangkat kisah Ande-Ande Lumut.', '2025-10-06', 6, '2025-10-06 14:00:44', '2025-10-06 14:00:44'),
(61, 'Tari Bedhaya', 'Tari Klasik', 'budaya_1759759460.jpg', 'https://www.tiktok.com/@bayjoee/video/7492764054356823303?is_from_webapp=1&sender_device=pc&web_id=7557998605446825480', 'Tari Bedhaya adalah tarian klasik sakral yang berasal dari lingkungan Keraton Surakarta dan Yogyakarta di Jawa Tengah. Tarian ini biasanya dibawakan oleh sembilan penari perempuan yang bergerak lembut dan penuh makna simbolis. Setiap gerak dalam Tari Bedhaya memiliki filosofi yang mendalam, menggambarkan keselarasan antara manusia, alam, dan Sang Pencipta. Gerakannya sangat halus, penuh konsentrasi, serta disertai ekspresi tenang dan anggun yang mencerminkan kehalusan budi perempuan Jawa. Iringan musik gamelan yang pelan dan tembang Jawa yang mendayu menciptakan suasana khidmat dan penuh kekhidmatan.\r\nKostum yang digunakan dalam Tari Bedhaya sangat indah dan berwibawa, biasanya berupa busana pengantin adat Jawa lengkap dengan paes, selendang, dan perhiasan tradisional. Tarian ini tidak hanya berfungsi sebagai hiburan, tetapi juga sebagai bentuk ritual yang melambangkan kesucian, kesetiaan, dan keharmonisan hidup. Dahulu, Tari Bedhaya hanya dipentaskan di keraton pada upacara tertentu seperti penobatan raja atau peringatan hari besar kerajaan. Kini, tarian ini menjadi salah satu warisan budaya yang dijaga kelestariannya dan menjadi simbol keagungan seni tari klasik Jawa Tengah.', '2025-10-06', 6, '2025-10-06 14:04:20', '2025-10-06 14:04:20'),
(62, 'Tari kuda lumping (Jaran Kepang)', 'Tari Klasik', 'budaya_1759759543.jpg', 'https://www.tiktok.com/@wongnogo0/video/7462690849231523079?is_from_webapp=1&sender_device=pc&web_id=7557998605446825480', 'Tari Kuda Lumping, atau dikenal juga dengan sebutan Jaran Kepang, adalah tarian tradisional yang sangat populer di berbagai daerah Jawa Tengah. Tarian ini menggambarkan keberanian dan semangat prajurit yang sedang berlatih perang sambil menunggang kuda. Para penari menggunakan properti berupa anyaman bambu berbentuk kuda yang disebut jaran kepang dan menampilkan gerakan lincah, dinamis, serta penuh tenaga. Iringan musik gamelan berpadu dengan tabuhan kendang dan gong menciptakan suasana semangat dan magis yang khas, sering kali membuat suasana pertunjukan terasa menegangkan namun memukau.\r\nSelain menonjolkan kekuatan fisik dan ketangkasan, Tari Kuda Lumping juga memiliki unsur spiritual yang kuat. Dalam beberapa pertunjukan, penari dapat mengalami trance atau kesurupan, yang dipercaya sebagai bentuk kekuatan gaib yang menyertai jalannya tarian. Kostum yang digunakan biasanya berwarna mencolok dengan hiasan kepala dan selendang yang menambah kesan gagah dan energik. Tari ini tidak hanya menjadi hiburan rakyat, tetapi juga memiliki makna simbolis tentang keberanian, semangat juang, serta hubungan manusia dengan dunia spiritual. Hingga kini, Tari Kuda Lumping tetap menjadi salah satu ikon budaya Jawa Tengah yang menarik dan sarat makna tradisi.', '2025-10-06', 6, '2025-10-06 14:05:43', '2025-10-06 14:05:43'),
(63, 'Tari Lengger', 'Tari Klasik', 'budaya_1759759639.jpg', 'https://www.tiktok.com/@pagubuganmelung/video/7525430822107680018?is_from_webapp=1&sender_device=pc&web_id=7557998605446825480', 'Tari Lengger adalah tarian tradisional yang berasal dari daerah Banyumas, Jawa Tengah. Tarian ini dikenal sebagai simbol kegembiraan, keindahan, dan keakraban masyarakat. Nama “Lengger” diyakini berasal dari kata elingo ngger yang berarti “ingatlah, Nak,” sebagai ajakan untuk selalu mengingat nilai-nilai kebaikan dalam hidup. Tari Lengger biasanya dibawakan oleh penari perempuan yang menari dengan lemah gemulai, diiringi musik gamelan Banyumasan yang berirama riang dan dinamis. Gerakan tarinya penuh kelembutan namun tetap energik, menggambarkan keceriaan dan semangat kehidupan masyarakat pedesaan.\r\nKostum penari Tari Lengger biasanya terdiri dari kemben, selendang berwarna cerah, serta riasan wajah yang anggun. Penari sering menari sambil mengayunkan selendang dengan gerakan yang luwes dan menggoda, menambah daya tarik visual bagi penonton. Selain sebagai hiburan, Tari Lengger juga memiliki makna spiritual yang dalam, yaitu sebagai bentuk rasa syukur kepada Tuhan dan penghormatan terhadap alam. Tarian ini sering ditampilkan dalam acara adat, hajatan, dan festival budaya. Hingga kini, Tari Lengger tetap menjadi salah satu ikon kesenian tradisional Banyumas yang mencerminkan keceriaan, keindahan, dan filosofi kehidupan masyarakat Jawa Tengah.', '2025-10-06', 6, '2025-10-06 14:07:19', '2025-10-06 14:07:19'),
(64, 'Tari Topeng Ireng', 'Tari Klasik', 'budaya_1759759711.jpg', 'https://www.tiktok.com/@hdpro_official/video/7523143635400002823?is_from_webapp=1&sender_device=pc&web_id=7557998605446825480', 'Tari Topeng Ireng adalah tarian tradisional yang berasal dari lereng Gunung Merbabu, tepatnya di daerah Magelang, Jawa Tengah. Tarian ini merupakan hasil perpaduan antara kesenian tradisional Jawa dengan unsur budaya modern dan religi. Kata “Topeng Ireng” berarti “topeng hitam”, yang melambangkan semangat juang dan kekuatan batin. Tari ini biasanya menggambarkan semangat para prajurit dalam berlatih perang serta semangat dakwah yang disampaikan melalui seni. Gerakannya energik, tegas, dan dinamis, menampilkan formasi barisan yang kompak dengan hentakan kaki yang kuat seirama dengan tabuhan musik yang keras dan bersemangat.\r\nPara penari mengenakan kostum berwarna cerah seperti merah, kuning, hijau, dan hitam, lengkap dengan hiasan kepala yang menyerupai bulu burung atau rumbai-rumbai warna-warni. Kostum ini memberi kesan gagah dan megah, menambah daya tarik pertunjukan. Iringan musiknya menggunakan perpaduan alat tradisional seperti kendang, gong, dan terompet, menciptakan suasana meriah dan membangkitkan semangat penonton. Tari Topeng Ireng tidak hanya menjadi tontonan hiburan, tetapi juga memiliki nilai moral dan spiritual tentang semangat, persatuan, dan perjuangan dalam menegakkan kebaikan. Hingga kini, tarian ini tetap lestari dan sering tampil dalam acara budaya maupun peringatan hari besar di Jawa Tengah.', '2025-10-06', 6, '2025-10-06 14:08:31', '2025-10-06 14:08:31'),
(65, 'Curug Lawe Benowo', 'Destinasi', 'budaya_1759759872.jpg', 'https://www.tiktok.com/@bonniebresserx/video/7292263523139341600?is_from_webapp=1&sender_device=pc&web_id=7557998605446825480', 'Curug Lawe Benowo merupakan destinasi wisata alam yang menakjubkan di Desa Kalisidi, Kecamatan Ungaran Barat, Kabupaten Semarang, Jawa Tengah. Tempat ini menawarkan dua air terjun yang berdekatan, yaitu Curug Lawe dan Curug Benowo, yang berada di lereng Gunung Ungaran. Untuk mencapai lokasi, pengunjung harus menempuh perjalanan sekitar dua kilometer dengan berjalan kaki melewati hutan bambu, sungai kecil, serta perkebunan kopi yang hijau dan menyejukkan. Meskipun cukup menantang, perjalanan menuju curug menjadi pengalaman seru karena udara di sepanjang jalur terasa segar dan pemandangannya indah. Curug Lawe memiliki ketinggian sekitar 30–40 meter dengan aliran air yang jatuh membentuk garis-garis putih menyerupai benang, sehingga disebut “Lawe” yang berarti benang putih dalam bahasa Jawa. Di sisi lain, Curug Benowo memiliki aliran air yang lebih lebar dan deras dengan kolam alami di bawahnya yang sering digunakan wisatawan untuk bermain air atau berfoto. Suara gemericik air berpadu dengan kicauan burung membuat suasana di sekitar curug terasa damai dan menenangkan. Dengan ketinggian sekitar 1.200 meter di atas permukaan laut, udara di kawasan Curug Lawe Benowo terasa sejuk dan segar, bahkan cenderung dingin pada pagi atau sore hari. Selain menikmati keindahan air terjun, pengunjung juga bisa beristirahat di gazebo sederhana atau berfoto di berbagai spot alami seperti jembatan bambu dan bebatuan besar di tepi sungai. Keindahan alam yang masih alami, udara pegunungan yang bersih, serta suasana tenang menjadikan Curug Lawe Benowo sebagai tempat yang cocok untuk wisata alam dan pelarian dari kesibukan kota.', '2025-10-06', 6, '2025-10-06 14:11:12', '2025-10-06 14:11:12'),
(66, 'Museum Batik Pekalongan', 'Destinasi', 'budaya_1759759985.jpg', 'https://www.tiktok.com/@tj_torry/video/7358123953350593797?is_from_webapp=1&sender_device=pc&web_id=7557998605446825480', 'Museum Batik Pekalongan merupakan salah satu destinasi wisata budaya yang terkenal di Kota Pekalongan, Jawa Tengah, yang dikenal sebagai “Kota Batik”. Museum ini menempati bangunan bersejarah peninggalan kolonial Belanda dan menyajikan berbagai koleksi batik dari seluruh Indonesia, mulai dari batik klasik Yogyakarta dan Solo hingga batik pesisir khas Pekalongan yang penuh warna. Di dalam museum, pengunjung dapat mempelajari sejarah perkembangan batik, mengenal alat-alat tradisional pembuat batik seperti canting dan malam, serta memahami makna filosofis di balik setiap motif batik yang kaya nilai seni dan budaya.\r\nSelain berkeliling melihat koleksi, pengunjung juga bisa mengikuti kegiatan membatik langsung di area workshop yang disediakan. Di sini, pengunjung diajak mencoba proses membuat batik mulai dari mencanting hingga pewarnaan, sehingga memberikan pengalaman menarik sekaligus edukatif. Dengan suasana bangunan yang nyaman, tata pameran yang rapi, dan nuansa budaya yang kuat, Museum Batik Pekalongan menjadi tempat yang cocok untuk mengenal lebih dalam warisan batik Indonesia yang telah diakui sebagai warisan budaya dunia oleh UNESCO.', '2025-10-06', 6, '2025-10-06 14:12:43', '2025-10-06 14:13:05'),
(68, 'Gudeg', 'Makanan Khas', 'budaya_1759831489.jpg', 'https://youtu.be/qR9tTeBTgSU?si=jFrEwtqkZvZS2zyT', 'Gudeg adalah makanan tradisional khas Yogyakarta dan Jawa Tengah yang terkenal dengan cita rasanya yang manis, gurih, dan kaya rempah. Hidangan ini terbuat dari nangka muda (gori) yang dimasak bersama santan, gula merah, daun salam, lengkuas, dan daun jati. Proses memasaknya membutuhkan waktu lama hingga bumbunya meresap sempurna dan menghasilkan warna cokelat keemasan yang khas dari daun jati. Gudeg biasanya disajikan dengan nasi putih, areh (santan kental), telur pindang, ayam opor, dan sambal goreng krecek sebagai pelengkapnya. Rasanya yang manis berpadu dengan gurihnya santan membuat hidangan ini sangat khas dan berbeda dari masakan daerah lain. Selain menjadi makanan sehari-hari, gudeg juga sering dijadikan oleh-oleh khas Yogyakarta dan Jawa Tengah karena bisa dikemas dalam bentuk kalengan atau kendil (tembikar). Sebagai simbol kuliner tradisional Jawa, gudeg mencerminkan karakter masyarakat Jawa yang lembut, sabar, dan sederhana, karena proses pembuatannya yang memerlukan ketelatenan dan waktu lama untuk menghasilkan rasa yang sempurna.', '2025-10-07', 6, '2025-10-07 10:04:49', '2025-10-07 10:04:49'),
(69, 'Nasi Liwet', 'Makanan Khas', 'budaya_1759831564.jpg', 'https://youtu.be/zcnY-qZXTug?si=UH5dE6e21Hv_hjXr', 'Nasi liwet adalah makanan tradisional khas Solo, Jawa Tengah, yang terkenal dengan cita rasanya yang gurih, lembut, dan harum. Hidangan ini terbuat dari beras yang dimasak dengan santan, daun salam, serai, dan sedikit garam, sehingga menghasilkan aroma yang wangi dan rasa gurih alami. Nasi liwet biasanya disajikan dengan sayur labu siam, suwiran ayam, telur pindang, areh (santan kental), dan kadang ditambah tempe atau tahu bacem sebagai pelengkap. Keistimewaan nasi liwet terletak pada cara penyajiannya yang sederhana namun khas. Biasanya disajikan di atas daun pisang, yang tidak hanya mempercantik tampilan, tetapi juga menambah aroma harum alami pada nasi. Makanan ini sering dinikmati saat sarapan atau acara kebersamaan, seperti kenduri dan selamatan, karena dianggap melambangkan kebersamaan dan kehangatan keluarga.\r\nDengan perpaduan rasa gurih dari santan dan lauk-pauk yang lengkap, nasi liwet menjadi salah satu kuliner kebanggaan masyarakat Jawa Tengah, khususnya kota Solo. Hidangan ini mencerminkan kesederhanaan dan kekayaan cita rasa tradisional Jawa yang tetap digemari hingga sekarang.', '2025-10-07', 6, '2025-10-07 10:06:04', '2025-10-07 10:06:04'),
(70, 'Mendoan', 'Makanan Khas', 'budaya_1759831631.jpg', 'https://vt.tiktok.com/ZSUFrb6XM/', 'Mendoan adalah makanan tradisional khas Banyumas, Jawa Tengah, yang terkenal dengan rasa gurihnya dan teksturnya yang lembut. Mendoan terbuat dari tempe tipis yang dilapisi dengan adonan tepung berbumbu lalu digoreng dalam minyak panas, tetapi hanya sebentar sehingga hasilnya tidak terlalu kering atau disebut “mendo,” yang dalam bahasa Banyumasan berarti setengah matang. Bumbu yang digunakan biasanya terdiri dari bawang putih, ketumbar, garam, daun bawang, dan kadang sedikit kunyit untuk menambah aroma dan warna. Ciri khas mendoan terletak pada tekstur luarnya yang lembut dan sedikit renyah, sementara bagian dalamnya masih hangat dan empuk. Biasanya mendoan disajikan selagi panas dan dinikmati dengan sambal kecap pedas atau cabai rawit segar. Makanan sederhana ini sering dijadikan teman minum teh atau kopi, terutama di sore hari. Selain rasanya yang lezat, mendoan juga mencerminkan kesederhanaan dan kreativitas masyarakat Banyumas dalam mengolah bahan makanan sehari-hari menjadi hidangan yang istimewa. Kini, mendoan tidak hanya populer di daerah asalnya, tetapi juga dikenal luas di berbagai daerah sebagai salah satu camilan khas Jawa Tengah yang gurih, lembut, dan menggugah selera.', '2025-10-07', 6, '2025-10-07 10:07:11', '2025-10-07 10:07:11');
INSERT INTO `data_budaya` (`id`, `nama`, `kategori`, `gambar`, `video_url`, `deskripsi`, `tanggal`, `admin_id`, `created_at`, `updated_at`) VALUES
(71, 'Nasi Gandul', 'Makanan Khas', 'budaya_1759831718.jpg', 'https://vt.tiktok.com/ZSUFhKgaA/', 'Nasi Gandul adalah makanan khas Pati, Jawa Tengah, yang terkenal dengan kuahnya yang gurih, kental, dan harum rempah. Hidangan ini terdiri dari nasi putih yang disajikan dengan irisan daging sapi atau jeroan, kemudian disiram dengan kuah santan berbumbu khas. Bumbu yang digunakan antara lain bawang merah, bawang putih, ketumbar, kemiri, lengkuas, daun salam, dan serai, yang dimasak hingga menghasilkan rasa gurih manis dan aroma yang menggugah selera. Keunikan Nasi Gandul terletak pada cara penyajiannya, yaitu di atas daun pisang yang diletakkan di atas piring. Daun pisang ini memberi aroma wangi alami pada nasi dan kuahnya. Selain itu, penyajian Nasi Gandul juga menggunakan sendok dari potongan daun pisang yang disebut “suru,” menambah kesan tradisional dan khas. Biasanya, Nasi Gandul disantap bersama tempe goreng, sambal, dan bawang goreng sebagai pelengkap. Rasa Nasi Gandul merupakan perpaduan antara gurih, manis, dan sedikit pedas, mencerminkan kekayaan bumbu dan kearifan lokal masyarakat Pati. Hidangan ini sering dinikmati sebagai menu makan siang atau malam, dan kini menjadi salah satu kuliner khas Jawa Tengah yang banyak dicari karena kelezatannya yang khas dan autentik.', '2025-10-07', 6, '2025-10-07 10:08:21', '2025-10-07 10:08:38'),
(72, 'Mangut Lele', 'Makanan Khas', 'budaya_1759831789.jpg', 'https://vt.tiktok.com/ZSUFkDYfk/', 'Mangut lele adalah makanan tradisional khas Jawa Tengah, terutama populer di daerah Semarang, Kendal, dan sekitarnya. Hidangan ini terbuat dari ikan lele yang telah digoreng atau diasap, kemudian dimasak dalam kuah santan kental yang diberi bumbu rempah seperti bawang merah, bawang putih, cabai, lengkuas, daun salam, serai, dan kemiri. Rasa mangut lele sangat khas — gurih, pedas, dan sedikit smoky bila menggunakan lele asap. Keunikan mangut lele terletak pada perpaduan aroma santan dan asap ikan yang menggugah selera. Kuahnya berwarna kuning kemerahan karena penggunaan cabai dan kunyit, dengan cita rasa pedas yang hangat di lidah. Biasanya, mangut lele disajikan bersama nasi hangat, lalapan segar, dan tempe goreng sebagai pelengkap. Makanan ini tidak hanya lezat, tetapi juga mencerminkan kekayaan bumbu dan kearifan lokal masyarakat Jawa Tengah dalam mengolah bahan sederhana menjadi hidangan istimewa. Di berbagai daerah, mangut lele sering disajikan dalam acara keluarga atau hajatan, karena rasanya yang menggugah selera dan cocok disantap bersama-sama.', '2025-10-07', 6, '2025-10-07 10:09:49', '2025-10-07 10:09:49'),
(73, 'Keraton Surakarta Hadiningrat', 'Destinasi', 'budaya_1759890736.jpg', 'https://www.tiktok.com/@notaestheticgirl/video/7320627240188808453?is_from_webapp=1&sender_device=pc&web_id=7557998605446825480', 'Keraton Surakarta Hadiningrat adalah istana resmi Kesunanan Surakarta yang berdiri pada tahun 1745 oleh Sri Susuhunan Pakubuwono II setelah pindah dari Kartasura. Keraton ini menjadi pusat pemerintahan, kebudayaan, dan adat istiadat Jawa yang sarat nilai-nilai filosofis. Arsitekturnya merupakan perpaduan antara gaya tradisional Jawa dengan sentuhan Eropa dan Islam, yang terlihat dari tata ruang, ukiran kayu, serta simbol-simbol sakral di setiap bangunannya. Kompleks keraton terdiri dari beberapa bagian penting seperti Pagelaran, Siti Hinggil, dan Kedhaton, yang masing-masing memiliki fungsi dan makna tersendiri dalam kehidupan kerajaan.\r\nSelain berfungsi sebagai tempat tinggal raja dan keluarganya, Keraton Surakarta juga menjadi pusat pelestarian seni dan budaya Jawa hingga saat ini. Di dalamnya masih sering diselenggarakan berbagai upacara adat, pertunjukan gamelan, tarian klasik, serta tradisi keagamaan seperti Sekaten. Keraton ini juga memiliki museum yang menyimpan koleksi pusaka kerajaan, perhiasan, senjata, dan peninggalan sejarah lainnya. Hingga kini, Keraton Surakarta Hadiningrat tidak hanya menjadi simbol kejayaan masa lalu, tetapi juga menjadi tempat penting untuk memahami warisan budaya dan sejarah bangsa Indonesia, khususnya kebudayaan Jawa.', '2025-10-08', 6, '2025-10-08 02:32:16', '2025-10-08 02:32:16'),
(74, 'Benteng Vastenburg', 'Destinasi', 'budaya_1759890807.jpg', 'https://www.tiktok.com/@bellaaeka_/video/7436630142782278967?is_from_webapp=1&sender_device=pc&web_id=7557998605446825480', 'Benteng Vastenburg adalah benteng peninggalan Belanda yang terletak di pusat Kota Surakarta, Jawa Tengah. Benteng ini dibangun sekitar tahun 1745 oleh pemerintah kolonial Belanda pada masa pemerintahan Gubernur Jenderal Baron van Imhoff. Fungsinya sebagai markas pertahanan Belanda sekaligus untuk mengawasi aktivitas Keraton Surakarta yang berada tidak jauh dari lokasi benteng. Bentuk bangunannya berbentuk persegi dengan empat bastion (menara pengawas) di setiap sudutnya. Dinding benteng terbuat dari bata tebal, dan di sekelilingnya terdapat parit yang dahulu berisi air sebagai sistem pertahanan tambahan.\r\nKini, Benteng Vastenburg menjadi salah satu situs bersejarah yang masih berdiri kokoh di tengah hiruk-pikuk modernisasi Kota Solo. Meskipun sempat terlantar, bangunan ini telah beberapa kali mengalami pemugaran dan kini sering digunakan untuk berbagai kegiatan budaya, pameran seni, hingga festival. Keberadaannya menjadi simbol perjuangan dan sejarah panjang hubungan antara kekuasaan kolonial Belanda dengan kerajaan lokal. Benteng Vastenburg tidak hanya memiliki nilai arsitektur yang tinggi, tetapi juga menjadi saksi bisu perkembangan sosial, politik, dan budaya di Surakarta dari masa penjajahan hingga era kemerdekaan.', '2025-10-08', 6, '2025-10-08 02:33:27', '2025-10-08 02:33:27'),
(75, 'Pantai Menganti', 'Destinasi', 'budaya_1759890885.jpg', 'https://www.tiktok.com/@inipapaya20/video/7552930262837972236?is_from_webapp=1&sender_device=pc&web_id=7557998605446825480', 'Pantai Menganti adalah salah satu pantai terindah di Kabupaten Kebumen, Jawa Tengah, yang terkenal dengan perpaduan pesona laut biru dan perbukitan hijau yang mengelilinginya. Pantai ini memiliki pasir putih bersih serta ombak yang cukup besar, menjadikannya cocok untuk wisatawan yang ingin menikmati panorama alam atau sekadar bersantai di tepi laut. Di sepanjang pantai terdapat tebing-tebing tinggi seperti Tebing Karang Bata dan Bukit Sigatel yang menawarkan pemandangan menakjubkan dari ketinggian. Dari atas bukit, pengunjung dapat menyaksikan hamparan laut selatan yang luas serta garis pantai yang berkelok indah.\r\nSelain keindahan alamnya, Pantai Menganti juga memiliki berbagai fasilitas penunjang wisata seperti gazebo, jembatan merah, area camping, serta spot foto dengan latar belakang laut dan perbukitan. Suasana di pantai ini masih alami dan asri, sehingga sangat cocok bagi pecinta alam atau wisatawan yang ingin menjauh sejenak dari keramaian kota. Di sekitar kawasan pantai juga terdapat perkampungan nelayan yang menambah kesan tradisional dan autentik. Dengan keindahan alam yang menawan dan suasana yang tenang, Pantai Menganti menjadi destinasi unggulan di Jawa Tengah yang wajib dikunjungi.', '2025-10-08', 6, '2025-10-08 02:34:45', '2025-10-08 02:34:45'),
(76, 'Air Terjun Grojogan Sewu', 'Destinasi', 'budaya_1759890948.jpg', 'https://www.tiktok.com/@parikesit_subi/video/7551444636842134796?is_from_webapp=1&sender_device=pc&web_id=7557998605446825480', 'Air Terjun Grojogan Sewu adalah salah satu objek wisata alam terkenal di Tawangmangu, Kabupaten Karanganyar, Jawa Tengah. Nama “Grojogan Sewu” berasal dari bahasa Jawa yang berarti “seribu pancuran,” menggambarkan banyaknya aliran air yang jatuh dari ketinggian. Air terjun ini memiliki ketinggian sekitar 81 meter dan dikelilingi oleh hutan tropis yang rimbun, menciptakan suasana sejuk dan alami. Di sekitar area air terjun terdapat jalan setapak dengan ribuan anak tangga yang membawa pengunjung melewati pepohonan besar dan udara pegunungan yang segar. Keindahan alam dan suara gemuruh air yang jatuh menjadikan Grojogan Sewu sebagai tempat favorit bagi pecinta alam dan fotografi.\r\nSelain menikmati panorama air terjun, pengunjung juga dapat menjumpai berbagai fasilitas wisata seperti area bermain, tempat istirahat, dan warung makan tradisional yang menjual kuliner khas Tawangmangu. Di kawasan ini juga hidup kera-kera liar yang menjadi daya tarik tersendiri bagi wisatawan. Suasana alami, udara yang sejuk, serta pemandangan pegunungan yang menawan menjadikan Air Terjun Grojogan Sewu sebagai destinasi wisata unggulan di lereng Gunung Lawu. Tempat ini bukan hanya menyuguhkan keindahan alam yang mempesona, tetapi juga memberikan pengalaman menyegarkan dan menenangkan bagi setiap pengunjung.', '2025-10-08', 6, '2025-10-08 02:35:48', '2025-10-08 02:35:48'),
(77, 'Kampung Batik Laweyan', 'Destinasi', 'budaya_1759891017.jpg', 'https://www.tiktok.com/@fianadewii/video/7497190061197266181?is_from_webapp=1&sender_device=pc&web_id=7557998605446825480', 'Kampung Batik Laweyan adalah salah satu kawasan bersejarah di Kota Surakarta (Solo), Jawa Tengah, yang dikenal sebagai pusat industri batik tertua di Indonesia. Kawasan ini sudah eksis sejak abad ke-16 dan menjadi tempat lahirnya para pengusaha batik ternama pada masa Kerajaan Pajang hingga era kolonial Belanda. Arsitektur bangunan di Laweyan memiliki keunikan tersendiri, memadukan gaya tradisional Jawa dengan sentuhan Eropa dan Tionghoa, yang tampak dari bentuk pintu, jendela, dan dinding tinggi khas rumah para juragan batik. Di sepanjang gang sempitnya, pengunjung dapat menemukan deretan rumah produksi batik, galeri seni, dan toko-toko yang menjual berbagai motif batik tulis maupun cap dengan corak khas Laweyan yang elegan dan penuh makna filosofi.\r\nSelain menjadi sentra ekonomi kreatif, Kampung Batik Laweyan juga menjadi simbol pelestarian budaya dan sejarah masyarakat Solo. Di sini, wisatawan tidak hanya bisa membeli batik, tetapi juga belajar langsung proses pembuatannya, mulai dari mencanting, mewarnai, hingga menjemur kain. Suasana kampung yang tenang dan bernuansa klasik menghadirkan pengalaman wisata edukatif dan budaya yang mendalam. Kini, Laweyan berkembang sebagai destinasi wisata heritage yang memadukan keindahan seni batik dengan nuansa sejarah dan kehidupan masyarakat tradisional Jawa yang masih lestari hingga sekarang.', '2025-10-08', 6, '2025-10-08 02:36:57', '2025-10-08 02:36:57'),
(78, 'Rumah Tajug', 'Rumah Adat', 'budaya_1759919863.jpg', 'https://youtu.be/TEA1Q82rB_E?si=iW3nEdcFle0-Ddk1', 'Rumah Tajug merupakan salah satu rumah adat khas Jawa Tengah yang memiliki bentuk atap menjulang tinggi menyerupai piramida atau gunung. Bentuk atap inilah yang disebut tajug dan menjadi ciri khas utama dari rumah ini. Rumah Tajug umumnya digunakan untuk bangunan yang bersifat suci atau tempat ibadah, seperti langgar, surau, dan masjid, karena masyarakat Jawa menganggap bentuk atap tajug melambangkan hubungan manusia dengan Tuhan. Karena itu, rumah Tajug jarang dijadikan sebagai rumah tinggal biasa, melainkan lebih banyak dipakai untuk kegiatan keagamaan dan spiritual.\r\nStruktur rumah Tajug dibuat dengan empat bidang atap yang sama besar dan bertemu di satu titik puncak. Bangunan ini biasanya berdiri di atas pondasi yang kuat dan terbuat dari kayu jati atau kayu nangka yang tahan lama. Bagian tengah ruangan bersifat terbuka tanpa sekat, melambangkan kesucian dan kebersamaan umat dalam beribadah. Di bagian sisi-sisinya terdapat ruang tambahan atau serambi yang digunakan untuk istirahat, bersuci, atau tempat menyimpan perlengkapan ibadah. Atap yang tinggi berfungsi menjaga sirkulasi udara agar ruangan tetap sejuk dan nyaman saat digunakan untuk kegiatan bersama.\r\nSelain bentuk dasarnya, rumah Tajug juga memiliki beberapa varian, seperti Tajug Lambang Sari, Tajug Mangkurat, Tajug Semar Tinandhu, dan Tajug Sinongsong. Setiap varian memiliki perbedaan pada bentuk atap dan hiasan puncaknya, tetapi semuanya tetap mempertahankan filosofi utama, yaitu mengarahkan pandangan manusia ke atas sebagai simbol pengabdian kepada Tuhan Yang Maha Esa. Filosofi inilah yang membuat rumah Tajug menjadi simbol spiritual dan kesakralan dalam budaya Jawa. Hingga kini, bentuk arsitektur Tajug masih banyak dijumpai pada masjid dan bangunan tradisional di berbagai daerah Jawa Tengah, sebagai wujud pelestarian nilai-nilai luhur masyarakat Jawa yang religius dan berbudaya.', '2025-10-08', 6, '2025-10-08 10:36:05', '2025-10-08 10:37:43'),
(79, 'Rumah Panggang Pe', 'Rumah Adat', 'budaya_1759919850.jpg', 'https://youtu.be/io4CDrsq8GY?si=p_9hplPsn6jvsoiQ', 'Rumah Panggang Pe adalah salah satu rumah adat khas Jawa Tengah yang memiliki bentuk sederhana namun fungsional. Bangunan ini memiliki atap limas yang menyerupai piramida kecil dan biasanya berdiri di atas tiang penyangga, tanpa dinding atau dengan dinding minimal, sehingga memungkinkan sirkulasi udara yang baik. Nama \"Panggang Pe\" sendiri berasal dari fungsi tradisional rumah ini sebagai tempat menjemur hasil pertanian, seperti singkong, jagung, daun teh, atau cengkeh.\r\nStruktur Rumah Panggang Pe sangat sederhana namun teratur. Bagian tengah rumah digunakan sebagai ruang utama untuk menjemur atau menyimpan hasil pertanian, sedangkan di sisi-sisinya terdapat ruang tambahan yang bisa dipakai untuk istirahat, menyimpan peralatan, atau ruang kerja kecil. Atap limas yang menjulang tinggi berfungsi untuk melindungi isi rumah dari panas matahari dan hujan, sekaligus menjaga kelembapan hasil pertanian.\r\nRumah Panggang Pe melambangkan kesederhanaan, kepraktisan, dan hubungan harmonis manusia dengan alam. Walaupun bentuknya sederhana, rumah ini mencerminkan kearifan lokal masyarakat Jawa dalam menyesuaikan arsitektur dengan kebutuhan sehari-hari dan lingkungan sekitar. Hingga kini, bentuk Rumah Panggang Pe masih banyak dijumpai di pedesaan Jawa Tengah sebagai bukti pelestarian budaya tradisional yang fungsional sekaligus indah.', '2025-10-08', 6, '2025-10-08 10:37:30', '2025-10-08 10:37:30');

--
-- Indexes for dumped tables
--

--
-- Indeks untuk tabel `data_budaya`
--
ALTER TABLE `data_budaya`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT untuk tabel yang dibuang
--

--
-- AUTO_INCREMENT untuk tabel `data_budaya`
--
ALTER TABLE `data_budaya`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=80;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
